# Generated by Django 5.0.1 on 2024-01-05 17:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0003_note_shared_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
